### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/Precip#1]
- Readme.md needs to say that GMT needs to be installed prior to pip install pygmt (on Mac I followed instructions using brew from https://docs.generic-mapping-tools.org/latest/install.html   and it worked fine)
- It is unclear where the GPM data are downloaded. We could have a GPM_DIR similar to WEATHER_DIR ?
- Download may be faster by downloading multiple files simultaneously.  ssara*bash uses `echo ${urls[@]} | xargs -n 1 -P $parallel timeout $timeout wget --continue --user $user --password $passwd`
- Rename `get_all.p`y to something with precip or precipitation in the name.  Maybe to  `plot_precip_all.py`, `plot_precipitation_all.py`  or `get_precip_all.py`.  I think for now I like `plot_precipitation_all.py`.
- How about we rename get_precipitation_lalo.py to `plot_precipitation.py` and the other command is `plot_precipitation_all.py` ?
- when you say `--save Merapi` the folder should be created (I am getting an error if teh folder does not exist)
- `get_all.py` produces 4 plots but I see only 3 *png?
- `get_all.py --no-show` does not work
- `get_all.py` --help needs to be updated.
- instead of `--save folder` have the choices `--save volcano-id` and `--save volcano-name` and then the images will be created in the corresponding directories
- rename `--nino` to `--elnino`
- for the file names, to be consistent with MinSAR (long names can become problems) lets use instead of `Merapi_2006-01-01_2007-01-01_annual.png` `Merapi_20060101_20070101_annual.png`.  If no --end-date is given  it would be `Merapi_20060101_XXXXXXXX_annual.png` and overwritten if it gets updated
- I see `--lalo E:W,S:N`. That is good, but how to do a point? Mintpy uses `--lalo` for that. Maybe use `--box-lalo` or something else?
-  rename repo from `precip` to `Precip` to be consistent with `MintPy` 

Updated (1):

-add link to where to find volcano names (e.g. is it MaunaLoa, Maunloa Mauna Loa?)

Updated (2):

-what is  --name  option?

**Comment by disilvestro** [comment]
- [ ] add guide for GMT installation on `README.md` file (**TbD** since i never needed to do this step)
- [ ] Create a `$GPM_DIR`. Do we have to export the variable through the python script? **TbD**
- [ ] Instead of `--save folder` have the choices `--save volcano-id` and `--save volcano-name` and then the images will be created in the corresponding directories. (Not very clear **TbD**
- [ ] add link to where to find volcano names. You mean the link to the `json` file? **TbD**
- [x] Rename `get_all.py` and `get_precipitation_lalo.py`
- [x] Change the global variables in CAPS
- [x] File names to be consistent with MinSAR (`Merapi_20060101_20070101_annual.png`). If no `--end-date` is given it would be `Merapi_20060101_XXXXXXXX_annual.png` and overwritten if it gets updated
- [x] Parallel download
- [x] Create the folder (when non-existent) when we specify it with the saving option i.e. `--save Merapi`
- [x] `get_all.py` produces all [4] plots.
- [x] Fix `get_all.py --no-show` 
- [x] Update **help**
- [x] Rename `--nino` to `--elnino`
- [x] `--lalo` option can already be used to select just a point (check examples). 
            One point `--lalo 19.5,-156.5` ; Area: `--lalo 19.5:21.5,-156.5:-154.5`
- [x] Rename `precip` to `Precip`

**Comment by falkamelung** [comment]
Does not seem relevant anymore

**Comment by falkamelung** [comment]
DONE
